export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const FORMULARIO_MOVIMIENTOS = 'FORMULARIO_MOVIMIENTOS';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';
export const OBTENER_CONFIGURACION = 'OBTENER_CONFIGURACION';

export const EMPLEADOS = 'EMPLEADOS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const LIMPIAR_EMPLEADOCREADO = 'LIMPIAR_EMPLEADOCREADO';
export const OBTENER_EMPLEADO = 'OBTENER_EMPLEADO';
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const VALIDAR_EMPLEADO = 'VALIDAR_EMPLEADO';
export const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';
export const EMPLEADO_ACTUAL = 'EMPLEADO_ACTUAL';
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO';
export const LIMPIAR_EMPLEADO = 'LIMPIAR_EMPLEADO';
export const LIMPIAR_ERRORES = 'LIMPIAR_ERRORES';

export const GRABAR_NOMINA = 'GRABAR_NOMINA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
